#!/usr/bin/env bash
# Install and setup nginx server
sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html

server_setup="server {
		listen 80 default_server;
		listen [::]:80 default_server;

		root /var/www/html;
		index index.html;
		}"
add_redirect="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"
echo "$server_setup" | sudo tee /etc/nginx/sites-available/default >/dev/null
sed -i "\$i\\$add_redirect" /etc/nginx/sites-available/default
sudo service nginx restart