#!/usr/bin/env bash
# A script that connects to my server using a ssh keypair
server="100.25.148.58"
user="ubuntu"

# Specify the private key file
private_key="~/.ssh/school"

# Use ssh with single-character flags
ssh -i $private_key $user@$server