#!/usr/bin/env bash
# A config file for ssh

Host web-01
    HostName 54.173.9.236
    User ubuntu
    IdentityFile ~/.ssh/school
    PasswordAuthentication no

Host web-02
    HostName 18.209.152.129
    User ubuntu
    IdentityFile ~/.ssh/school
    PasswordAuthentication no
